version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes: 
      - './backend:/usr/src/app'
    tty: true
    stdin_open: true
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on: 
      - db

  db:
    image: postgres:13
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password