source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Principal Gems
ruby '3.1.1'
gem 'bootsnap', require: false
gem 'rails', '~> 7.0.2', '>= 7.0.2.3'
gem 'sprockets-rails'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Web server
gem 'puma', '~> 5.0'

# DB
gem 'pg', '~> 1.1'
gem 'ridgepole'

# Linter
gem 'rubocop'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
